#+LATEX_CLASS: lecture-document-udlap
#+TITLE:
#+OPTIONS: H:1 toc:nil
#+HTML_DOCTYPE:

#+BEGIN_EXPORT latex
\renewcommand{\thecareer}{Computer Systems Engineering}
\renewcommand{\thedocumenttitle}{Weeks 02, 03}
\renewcommand{\theterm}{Spring 2017}
\renewcommand{\thecoursename}{Network and Server Laboratory}
\renewcommand{\thecoursecode}{LIS4091}
\makeheadfoot
#+END_EXPORT

* Purpose
This document describes the content and activities for Weeks 02 and 03 of the course
*Network and Server Administration* with code *LI4091*.

* Instructor-led Training Activities
   1. Create a directory in your home directory called projects.  In the
      projects directory, create nine empty files that are named house1, house2,
      house3, and so on to house9. Assuming there are lots of other files in
      that directory, come up with a single argument to ls that would list just
      those nine files.
      1. Create from 1 to 3 manually
      2. Remove them on one command
      3. Create from 1 to 9 with a loop

   2. Make the ~$HOME/projects/houses/doors/~ directory
      path. Create the following empty files within this directory path (try
      using absolute and relative paths from your home directory):
      #+begin_src shell :results silent :export code
      $HOME/projects/houses/bungalow.txt
      $HOME/projects/houses/doors/bifold.txt
      $HOME/projects/outdoors/vegetation/landscape.txt
      #+end_src

   3. Copy the files house1 and house5 to the ~$HOME/projects/houses/~ directory.

   4. Recursively copy the ~/usr/share/doc/initscripts*~
      directory to the ~$HOME/projects/~
      directory. Maintain the current date/time stamps and permissions.

   5. Recursively list the contents of the ~$HOME/projects/~ directory. Pipe the
      output to the less command so you can page through the output.

   6. Remove the files house6, house7, and house8 without being prompted.

   7. Move house3 and house4 to the
      ~HOME/projects/houses/doors~ directory.

   8. Remove the ~$HOME/projects/houses/doors~ directory
      and its contents.

   9. Change the permissions on the
      ~$HOME/projects/house2~ file so it can be read and written by the
      user who owns the file, only read by the group, and have no permission for
      others.

   10. Recursively change permissions of the
       ~$HOME/projects/~ directory so nobody has write permission to any
       files or directory beneath that point in the filesystem.

   11. Make a shell script that prints all odd numbers between 1 and 99

* Self-pace Learning Activities

1. Watch the following material:
   + [[https://youtu.be/hwrnmQumtPw?list=PLtNNgm3QdKeSQP1Fh92OyvsMvDlpAO-7m][Shell Scripting Tutorial]]
